/* soapBasicHttpBinding_USCOREILicenseServerServiceProxy.h
   Generated by gSOAP 2.7.17 from test.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapBasicHttpBinding_USCOREILicenseServerServiceProxy_H
#define soapBasicHttpBinding_USCOREILicenseServerServiceProxy_H
#include "soapH.h"

class SOAP_CMAC BasicHttpBinding_USCOREILicenseServerServiceProxy : public soap
{ public:
	/// Endpoint URL of service 'BasicHttpBinding_USCOREILicenseServerServiceProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	BasicHttpBinding_USCOREILicenseServerServiceProxy();
	/// Constructor with copy of another engine state
	BasicHttpBinding_USCOREILicenseServerServiceProxy(const struct soap&);
	/// Constructor with engine input+output mode control
	BasicHttpBinding_USCOREILicenseServerServiceProxy(soap_mode iomode);
	/// Constructor with engine input and output mode control
	BasicHttpBinding_USCOREILicenseServerServiceProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~BasicHttpBinding_USCOREILicenseServerServiceProxy();
	/// Initializer used by constructors
	virtual	void BasicHttpBinding_USCOREILicenseServerServiceProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Force close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'CheckLogin' (returns error code or SOAP_OK)
	virtual	int CheckLogin(_ns1__CheckLogin *ns1__CheckLogin, _ns1__CheckLoginResponse *ns1__CheckLoginResponse);
};
#endif
