/* soapBasicHttpBinding_USCOREILicenseServerServiceProxy.cpp
   Generated by gSOAP 2.7.17 from test.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapBasicHttpBinding_USCOREILicenseServerServiceProxy.h"

BasicHttpBinding_USCOREILicenseServerServiceProxy::BasicHttpBinding_USCOREILicenseServerServiceProxy()
{	BasicHttpBinding_USCOREILicenseServerServiceProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

BasicHttpBinding_USCOREILicenseServerServiceProxy::BasicHttpBinding_USCOREILicenseServerServiceProxy(const struct soap &_soap) : soap(_soap)
{ }

BasicHttpBinding_USCOREILicenseServerServiceProxy::BasicHttpBinding_USCOREILicenseServerServiceProxy(soap_mode iomode)
{	BasicHttpBinding_USCOREILicenseServerServiceProxy_init(iomode, iomode);
}

BasicHttpBinding_USCOREILicenseServerServiceProxy::BasicHttpBinding_USCOREILicenseServerServiceProxy(soap_mode imode, soap_mode omode)
{	BasicHttpBinding_USCOREILicenseServerServiceProxy_init(imode, omode);
}

void BasicHttpBinding_USCOREILicenseServerServiceProxy::BasicHttpBinding_USCOREILicenseServerServiceProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://www.w3.org/2003/05/soap-envelope", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://www.w3.org/2003/05/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns3", "http://schemas.microsoft.com/2003/10/Serialization/", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	this->namespaces = namespaces;
}

BasicHttpBinding_USCOREILicenseServerServiceProxy::~BasicHttpBinding_USCOREILicenseServerServiceProxy()
{ }

void BasicHttpBinding_USCOREILicenseServerServiceProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_noheader()
{	header = NULL;
}

const SOAP_ENV__Fault *BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_fault()
{	return this->fault;
}

const char *BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_close_socket()
{	return soap_closesock(this);
}

void BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *BasicHttpBinding_USCOREILicenseServerServiceProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int BasicHttpBinding_USCOREILicenseServerServiceProxy::CheckLogin(_ns1__CheckLogin *ns1__CheckLogin, _ns1__CheckLoginResponse *ns1__CheckLoginResponse)
{	struct soap *soap = this;
	struct __ns1__CheckLogin soap_tmp___ns1__CheckLogin;
	const char *soap_action = NULL;
	if (!soap_endpoint)
		soap_endpoint = "http://gamebook:8890/LicenseServerService.svc";
	soap_action = "http://tempuri.org/ILicenseServerService/CheckLogin";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CheckLogin.ns1__CheckLogin = ns1__CheckLogin;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CheckLogin(soap, &soap_tmp___ns1__CheckLogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CheckLogin(soap, &soap_tmp___ns1__CheckLogin, "-ns1:CheckLogin", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CheckLogin(soap, &soap_tmp___ns1__CheckLogin, "-ns1:CheckLogin", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CheckLoginResponse)
		return soap_closesock(soap);
	ns1__CheckLoginResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CheckLoginResponse->soap_get(soap, "ns1:CheckLoginResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
